services:
  api:
    platform: linux/arm64/v8
    build:
      context: .
      target: builder
    container_name: fastapi-application
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    restart: "no"
    depends_on:
      - cache
  cache:
    platform: linux/arm64/v8
    image: "memcached:latest"
    ports:
      - '11211:11211'
    command: ["memcached"]
