services:
  api:
    platform: linux/arm64/v8
    build:
      context: .
      target: builder
    container_name: fastapi-application
    # environment:
    #   - CACHE_DSN=memcached:11211
    ports:
      - 8000:8000
    restart: "no"
    depends_on:
      - memcached
  memcached:
    platform: linux/arm64/v8
    image: memcached:latest
    restart: always
    ports:
      - 11211:11211
